function boardFAQlist(){
			return '<div id="boardFAQwrapper">'
				+'<ul class="kal-result-ss-count">'
					+'<li>전체'
						+'<span class="kal-result-ss-before"></span>'
					+'</li>'
					+'<li>전체</li>'
					+'<li>(268)</li>'
				+'</ul>'
				+'</div>'
				+'<div class="kal-faq-ss-list-border">'
					+'<ul class=" kal-list-ss-ul">'
						+'<li class="kal-list-ss-li">'
							+'<a href="javascript:void(0);" id="kal-faqList-a">'
								+'Q1. : 모닝캄 프리미엄 클럽 회원이 보너스 항공권을 구매하는 경우 성수기에도 비수기 마일리지가 적용된다는데, 가족도 동일하게 비수기 마일리지를 적용 받을 수 있나요?'
								+'<span class="kal-list-ss-plus"></span>'
							+'</a>'
				+'<div id="kal-faq-ss-answer" class="kal-list-ss-answer">'
					+'<div>'
						+'<span>A:</span>'
						+'<span class="kal-list-ss-ans">Answer</span>'
					+'<p>모닝캄 프리미엄 회원이 가족에게 마일리지를 양도해 보너스를 발급하는 경우에만 비수기 마일리지를 적용할 수 있습니다. </p>'
					+'</div>'
				+'</div>'
				+'</li>'
				+'<li class="kal-list-ss-li">'
					+'<a href="javascript:void(0);" id="kal-faqList-a">'
					+'Q1. : 모닝캄 프리미엄 클럽 회원이 보너스 항공권을 구매하는 경우 성수기에도 비수기 마일리지가 적용된다는데, 가족도 동일하게 비수기 마일리지를 적용 받을 수 있나요?'
						+'<span class="kal-list-ss-plus"></span>'
							+'</a>'
							+'<div id="kal-faq-ss-answer" class="kal-list-ss-answer">'
								+'<div>'
								+'<span>A:</span>'
								+'<span class="kal-list-ss-ans">Answer</span>'
								+'<p>모닝캄 프리미엄 회원이 가족에게 마일리지를 양도해 보너스를 발급하는 경우에만 비수기 마일리지를 적용할 수 있습니다. </p>'
							+'</div>'
					+'</div>'
					+'</li>'
				+'<li class="kal-list-ss-li">'
						+'<a href="javascript:void(0);" id="kal-faqList-a">'
						+'Q1. : 모닝캄 프리미엄 클럽 회원이 보너스 항공권을 구매하는 경우 성수기에도 비수기 마일리지가 적용된다는데, 가족도 동일하게 비수기 마일리지를 적용 받을 수 있나요?'
							+'<span class="kal-list-ss-plus"></span>'
								+'</a>'
									+'<div id="kal-faq-ss-answer" class="kal-list-ss-answer">'
									+'<div>'
								+'<span>A:</span>'
							+'<span class="kal-list-ss-ans">Answer</span>'
						+'<p>모닝캄 프리미엄 회원이 가족에게 마일리지를 양도해 보너스를 발급하는 경우에만 비수기 마일리지를 적용할 수 있습니다. </p>'
						+'</div>'
					+'</div>'
					+'</li>'
					+'<li class="kal-list-ss-li">'
						+'<a href="javascript:void(0);" id="kal-faqList-a">'
							+'Q1. : 모닝캄 프리미엄 클럽 회원이 보너스 항공권을 구매하는 경우 성수기에도 비수기 마일리지가 적용된다는데, 가족도 동일하게 비수기 마일리지를 적용 받을 수 있나요?'
								+'<span class="kal-list-ss-plus"></span>'
									+'</a>'
										+'<div id="kal-faq-ss-answer" class="kal-list-ss-answer">'
											+'<div>'
										+'<span>A:</span>'
									+'<span class="kal-list-ss-ans">Answer</span>'
							+'<p>모닝캄 프리미엄 회원이 가족에게 마일리지를 양도해 보너스를 발급하는 경우에만 비수기 마일리지를 적용할 수 있습니다. </p>'
						+'</div>'
					+'</div>'
					+'</li>'
					+'<li class="kal-list-ss-li">'
						+'<a href="javascript:void(0);" id="kal-faqList-a">'
							+'Q1. : 모닝캄 프리미엄 클럽 회원이 보너스 항공권을 구매하는 경우 성수기에도 비수기 마일리지가 적용된다는데, 가족도 동일하게 비수기 마일리지를 적용 받을 수 있나요?'
								+'<span class="kal-list-ss-plus"></span>'
									+'</a>'
										+'<div id="kal-faq-ss-answer" class="kal-list-ss-answer">'
											+'<div>'
										+'<span>A:</span>'
								+'<span class="kal-list-ss-ans">Answer</span>'
							+'<p>모닝캄 프리미엄 회원이 가족에게 마일리지를 양도해 보너스를 발급하는 경우에만 비수기 마일리지를 적용할 수 있습니다. </p>'
						+'</div>'
						+'</div>'
					+'</li>'
					+'</ul>';
		}
function mainGnb(image){
			return '<div class="kal-main-gnb">'
			+	'<div class="kal-main-logo">'
			+		'<a id="kal-logo" href="javascript:void(0)"><img src="'+image+'/main/koreanAirLogo.png"/></a>'
			+	'</div>'
			+	'<div class="kal-main-right-menu">'
			+		'<button class="kal-main-right-menu-reservation-btn">항공권 예매</button>'
			+		'<button class="kal-main-right-menu-skypass-btn">스카이패스</button>'
			+		'<button class="kal-main-right-menu-service-btn">서비스 안내'
			+			'<div class="kal-service-btn-content">'
			+				'<a class="after-login-kal-service-btn-content-question" href="#">질문하기</a>'
			+				'<a class="after-login-kal-service-btn-content-faq" href="#">FAQ 게시판</a>'
			+				'<a class="kal-service-btn-content-review" href="#">리뷰 게시판</a>'
			+			'</div>'
			+		'</button>'
			+		'<button class="kal-main-right-menu-promotion-btn">프로모션/여행상품</button>'
			+	'</div>'
			+'</div>';
		}
function boardQna(authId){
			return '<div id="kal-faq-ss-img" class="kal-faq-ss-bg">'
			+'<div class="kal-faq-ss-title">'
			+'<h2>Q&A</h2>'
			+'</div>'
			+'<div class="kal-faq-ss-wrapper">'
					+'<div class="kal-faq-ss-h2">'
						+'<h2>질문하기</h2>'
							+'<div class="kal-qna-ss-writerbox">'
								+'<div class="kal-qna-ss-write"><div>'
									+'<br />'
										+'<span class="kal-qna-ss-select-text">질문작성</span>'
										 +'</div>'
											+'</div>'
											+'<div class="kal-qna-ss-qnaWriter">작성자 : '+authId+'</div>'
												+'<form action="" class="kal-faq-ss-form">'
													+'<div class="kal-faq-ss">'
														+'<label for="category-select" class="kal-qna-ss-select-typeText">상위분류</label>'
															+'<div class="kal-faq-ss-align">'
																+'<select name="" id="category-select" class="kal-qna-ss-select-style">'
																+'<option value="전체">전체</option>'
																+'<option value="항공권 예약/구매/환불">항공권 예약/구매/환불</option>'
																+'<option value="스카이패스">스카이패스</option>'
																+'<option value="홈페이지 이용">홈페이지 이용</option>'
																+'<option value="공항 서비스">공항 서비스</option>'
																+'<option value="수하물 관련">수하물 관련</option>'
																+'<option value="객실 서비스">예매</option>'
																+'<option value="기내식">객실 서비스</option>'
																+'<option value="제휴 항공사">제휴 항공사</option>'
																+'<option value="기타">기타</option>'
															+'</select>'
													+'</div>'
												+'<div class="kal-qna-ss-text">'
												+'<input name="" id="" class="kal-qna-ss-text-style" placeholder="질문하기" type="text">'
												+'</div>'
												+'</div>'
												+'<button id="kal-all-ss-add-button" class="kal-qna-ss-button-ques" type="button">질문하기'
												+'<span></span>'
												+'</button>'
												+'<button id="kal-all-ss-del-button" class="kal-qna-ss-button-ques" type="button">질문지우기'
												+'<span></span>'
												+'</button>'
												+'</form>'
												+'<div id="kal-qna-ss-question"></div>'
												+'</div>'
												+'</div>'
											+'</div>'
										'</div>';  
										}
function subGnbAfterLogin(image){
			return '<div class="kal-after-login-sub-gnb">'
			+	'<div class="kal-after-login-sub-left-menu">'
			+		'<button class="kal-after-login-sub-left-menu-region-select-btn">국가/언어<img src="'+image+'/main/btn-regionSelect.png"/></button>'
			+		'<span class="kal-after-login-sub-left-menu-text1"><img src="'+image+'/main/korea-flag.gif">대한민국   ｜</span>'
			+		'<span class="kal-after-login-sub-left-menu-text2">한국어</span>'
			+		'<a class="kal-after-login-sub-left-menu-text3" href="#">English</a>'
			+	'</div>'
			+	'<div class="kal-after-login-sub-right-menu">'
			+		'<a class="kal-after-login-sub-right-menu-logout" href="#">로그아웃   ｜</a>'
			+		'<a class="kal-after-login-sub-right-menu-mypage" href="">&nbsp마이페이지    ｜</a>'
			+		'<a class="kal-after-login-sub-right-menu-myregist" href="">&nbsp나의 예약 &nbsp&nbsp</a>'
			+		'<input class="kal-after-login-sub-right-menu-search" type="text" placeholder="검색"/>'
			+		'<a class="kal-after-login-sub-right-menu-search-icon" href="#"><img src="'+image+'/main/icon-search.png"/></a>'
			+	'</div>'	
			+'</div>';
		}
function mainFooter(image){
			return '<div class="kal-footer">'
			+	'<div class="kal-footer-wrap">'
			+		'<div class="kal-footer-left-content">'
			+			'<div class="kal-footer-left-content-menu">'
			+				'<div class="kal-footer-left-content-menu-1">'
			+					'<h2>규정 및 약관</h2>'
			+					'<ul>'
			+						'<li class="kal-footer-left-content-menu-1-li1"><a href="#">개인정보처리방침</a></li>'
			+						'<li class="kal-footer-left-content-menu-1-li2"><a href="#">회원약관</a></li>'
			+						'<li class="kal-footer-left-content-menu-1-li3"><a href="#">운송약관</a></li>'
			+						'<li class="kal-footer-left-content-menu-1-li4"><a href="#">소비자 안전관련 정보</a></li>'
			+					'</ul>'
			+				'</div>'
			+				'<div class="kal-footer-left-content-menu-2">'
			+					'<h2>서비스 정보</h2>'
			+					'<ul>'
			+						'<li class="kal-footer-left-content-menu-2-li1"><a href="#">고객 서비스</a></li>'
			+						'<li class="kal-footer-left-content-menu-2-li2"><a href="#">고객 안내 서비스</a></li>'
			+						'<li class="kal-footer-left-content-menu-2-li3"><a href="#">서비스 수수료 안내</a></li>'
			+						'<li class="kal-footer-left-content-menu-2-li4"><a href="#">e 서식함</a></li>'
			+					'</ul>'
			+				'</div>'
			+				'<div class="kal-footer-left-content-menu-3">'
			+					'<h2>고객 지원</h2>'
			+					'<ul>'
			+						'<li class="kal-footer-left-content-menu-3-li1"><a href="#">지점 연락처</a></li>'
			+						'<li class="kal-footer-left-content-menu-3-li2"><a href="#">고객의 말씀</a></li>'
			+						'<li class="kal-footer-left-content-menu-3-li3"><a href="#">FAQ</a></li>'
			+						'<li class="kal-footer-left-content-menu-3-li4"><a href="#">채팅 서비스</a></li>'
			+					'</ul>'
			+				'</div>'
			+				'<div class="kal-footer-left-content-menu-4">'
			+					'<h2>회사 소개</h2>'
			+					'<ul>'
			+						'<li class="kal-footer-left-content-menu-4-li1"><a href="#">대한항공에 대하여</a></li>'
			+						'<li class="kal-footer-left-content-menu-4-li2"><a href="#">경영 재무 정보</a></li>'
			+						'<li class="kal-footer-left-content-menu-4-li3"><a href="#">녹색 경영</a></li>'
			+						'<li class="kal-footer-left-content-menu-4-li4"><a href="#">사회공헌활동</a></li>'
			+					'</ul>'
			+				'</div>'
			+			'</div>'
			+			'<div class="kal-footer-left-content-address">'
			+				'<div class="kal-footer-left-content-address-addr">'
			+				'</div>'
			+				'<div class="kal-footer-left-content-address-sns">'
			+					'<a href="#"><img src="'+image+'/main/icon-fb.png"/></a>'
			+					'<a href="#"><img src="'+image+'/main/icon-tw.png"/></a>'
			+					'<a href="#"><img src="'+image+'/main/icon-inst.png"/></a>'
			+					'<a href="#"><img src="'+image+'/main/icon-gp.png"/></a>'
			+				'</div>'
			+			'</div>'
			+		'</div>'
			+		'<div class="kal-footer-right-content">'
			+		'</div>'
			+	'</div>'
			+'</div>';
	}
	function question(qna){
		return '<div class="kal-qna-ss-list-border">'
		+			'<ul id="kal-qna-ss-ul" class="kal-qna-ss-ul">'
		+						qna
		+			'</ul>'
		+		'</div>';
	}
	function answer(ans){
		return '<div id="kal-faq-ss-answer" class="kal-list-ss-answer">'
		+			'<div tabindex="-1">'
		+				'<span>A:</span>'
		+					'<span class="kal-list-ss-ans">Answer</span>'
		+						'<p id="kal=qna-ss-p">'+ans+'</p>'
		+			'</div>'
		+		'</div>'
	}
